# configs/config_base.yaml
# ============================
## Template (shared between reader and writer)
template:
  file_path: "data/templates/Ram 2026_Owen Testing.xlsx"
  header_row: 16
  po_col: "B"
  po_stop_marker: "Previous Period Invoices"
  cost_center_col: "A"
  cost_center_start_row: 9
# ============================
## Forecast Reader
forecast_reader:
  file_paths:
    - "data/forecasts/Other_Vendors_Forecasts.xlsx"
    - "data/forecasts/2026-Feb-IBM Forecast_AP02.xlsx"
  po_col: "PO #"
# ============================
## Transactional Detail Reader
transactional_detail_reader:
  file_path: "data/transactional/TIES AP03 2026.xlsx"
  required_cols:
    - "PO Number"
    - "Month"
    - "GL Transaction Amount"
  valid_types:
    - "Actual"
    - "Accrual"
    - "Reversal"
  colmap:
    po: "PO Number"
    month: "Month"
    amount: "GL BER Corp Amount"
    classifier: "AP Voucher Number"
    cost_center: "Cost Center*"
    wbs: "WBS Element"
    type: "Type"
# ============================
## Template Writer
template_writer:
  output_path: "data/templates/template_AP03.xlsx"
  overwrite: False
  dec_acc_reversal_col: "N"
  forecast_source_cols:
    - "PO #"
    - "Jan 2026 - FTotal"
    - "Feb 2026 - FTotal"
    - "March 2026 - FTotal"
    - "April 2026 - FTotal"
    - "May 2026 - FTotal"
    - "June 2026 - FTotal"
    - "July 2026 - FTotal"
    - "Aug 2026 - FTotal"
    - "Sep 2026 - FTotal"
    - "Oct 2026 - FTotal"
    - "Nov 2026 - FTotal"
    - "Dec 2026 - FTotal"
  transactional_source_cols:
    - "PO Number"
    - "Accounting Period"
    - "AP Voucher Number"
    - "Vendor Name"
    - "WBS Element"
    - "GL Invoice Date"
    - "GL Posting Date"
    - "GL Line Description"
    - "Description"
    - "GL Transaction Amount"
    - "GL BER Corp Amount"
    - "Month"
    - "AP01"
    - "AP02"
    - "AP03"
    - "Type"