# configs/config_base.yaml

## Forecast Reader
forecast_reader:
  file_paths:
    - "data/forecasts/Other_Vendors_Forecasts.xlsx"

## Transactional Detail Reader
transactional_detail_reader:
  file_path: "data/transactional/TIES AP03 2026.xlsx"
  
  required_cols:
    - "PO Number"
    - "Month"
    - "GL Transaction Amount"
  
  valid_types:
    - "Actual"
    - "Accrual"
    - "Reversal"
  
  colmap:
    po: "PO Number"
    month: "Month"
    amount: "AP03"
    classifier: "AP Voucher Number"
    type: "Type"

## Template Writer
template_writer:
  file_path: "data/templates/financial_template_v2_2026.xlsx"
  header_row: 14
  po_column: "B"
  dec_acc_reversal_col: "N"