# configs/config_v1.yaml

## Forecast Reader
forecast_reader:
  file_paths:
    - "data/2025-11-IBM Forecast.xlsx"

## Transactional Detail Reader
transactional_detail_reader:
  file_path: "data/C-TIES AP09 2025.xlsx"

## Template Writer
template_writer:
  file_path: "data/templates/financial_template_v1.xlsx"
